environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - set PYTHONPATH=%CD%\pyblish\pythonpath
  - set PATH=C:\Program Files (x86)\Inno Setup 5;%PATH%

  - pip install -r requirements.txt
  - pip install git+git://github.com/pyqt/python-qt5.git
  - git clone https://github.com/pyblish/pyblish
  - powershell .appveyor/install_innosetup.ps1

build_script:
  - echo Building..
  - build-exe.bat
  - build-installer.bat
  - dir

artifacts:
  - path: dist\*
    name: installer

deploy:
  provider: Environment
  name: GitHub
  on:
    branch: master
    appveyor_repo_tag: true